In [1]:
from util.load_dataframes import load_dataframe_vacas, load_dataframe_patadas, load_dataframe_inventario, load_dataframe_reporte


df = load_dataframe_vacas('datos/registros_sesiones_merged.csv')
df = df.sample(frac=1)
df.head()

          ID Fecha y hora de inicio              Main                   \
     ID Vaca                  fecha      hora  Acción Duración (mm:ss)
582     1233             2025-05-23  01:21:00  Ordeño            05:45
4067    6178             2025-05-11  02:40:00  Ordeño            07:30
4421    6191             2025-07-11  13:34:00  Ordeño            12:30
193     1204             2025-06-16  23:54:00  Ordeño            09:02
2888    2078             2025-06-30  22:29:00  Ordeño            06:40

                               Estado                    \
     Producción (kg) Número de ordeño Patada Incompleto
582             7.09              1.0      0          0
4067           24.13              1.0      0          0
4421           27.25              2.0      0          0
193             8.80              1.0      0         TI
2888            9.33              3.0      0          0

                             ... Flujos máximos (kg/min)              \
     Pezones no encontrados  ...                      TI    TD Total
582                       0  ...                    1.14  1.80  5.82
4067                      0  ...                    1.98  1.86  8.34
4421                      0  ...                    4.26  1.56  8.16
193                      TI  ...                    0.00  2.22  6.42
2888                      0  ...                    1.56  1.44  5.40

     Producciones (kg)                            Misc
                    DI    DD    TI    TD  Total  EO/PO Destino Leche
582               2.21  1.74  0.73  2.41   7.09  VMS 3        Tanque
4067              4.47  7.93  6.04  5.69  24.13  VMS 2        Tanque
4421              3.93  5.22  8.48  9.62  27.25  VMS 3        Tanque
193               2.74  2.53  0.00  3.53   8.80  VMS 3        Tanque
2888              3.11  2.13  2.72  1.37   9.33  VMS 3        Tanque

[5 rows x 38 columns]

In [2]:
from util.split_dataframes import split_dataframe

train, test, val = split_dataframe(df, 70, 15, 15)

In [3]:
train.head()

          ID Fecha y hora de inicio              Main                   \
     ID Vaca                  fecha      hora  Acción Duración (mm:ss)
582     1233             2025-05-23  01:21:00  Ordeño            05:45
4067    6178             2025-05-11  02:40:00  Ordeño            07:30
4421    6191             2025-07-11  13:34:00  Ordeño            12:30
193     1204             2025-06-16  23:54:00  Ordeño            09:02
2888    2078             2025-06-30  22:29:00  Ordeño            06:40

                               Estado                    \
     Producción (kg) Número de ordeño Patada Incompleto
582             7.09              1.0      0          0
4067           24.13              1.0      0          0
4421           27.25              2.0      0          0
193             8.80              1.0      0         TI
2888            9.33              3.0      0          0

                             ... Flujos máximos (kg/min)              \
     Pezones no encontrados  ...                      TI    TD Total
582                       0  ...                    1.14  1.80  5.82
4067                      0  ...                    1.98  1.86  8.34
4421                      0  ...                    4.26  1.56  8.16
193                      TI  ...                    0.00  2.22  6.42
2888                      0  ...                    1.56  1.44  5.40

     Producciones (kg)                            Misc
                    DI    DD    TI    TD  Total  EO/PO Destino Leche
582               2.21  1.74  0.73  2.41   7.09  VMS 3        Tanque
4067              4.47  7.93  6.04  5.69  24.13  VMS 2        Tanque
4421              3.93  5.22  8.48  9.62  27.25  VMS 3        Tanque
193               2.74  2.53  0.00  3.53   8.80  VMS 3        Tanque
2888              3.11  2.13  2.72  1.37   9.33  VMS 3        Tanque

[5 rows x 38 columns]

In [4]:
test.head()

          ID Fecha y hora de inicio              Main                   \
     ID Vaca                  fecha      hora  Acción Duración (mm:ss)
272     1221             2025-03-08  14:21:00  Ordeño            07:06
5423    8712             2025-04-02  09:15:00  Ordeño            11:13
1541    1613             2025-06-25  10:18:00  Ordeño            09:15
812     1554             2025-04-08  09:10:00  Ordeño            09:05
3799    6036             2025-05-27  16:50:00  Ordeño            08:19

                               Estado                    \
     Producción (kg) Número de ordeño Patada Incompleto
272            16.18              2.0      0          0
5423            8.56              1.0     TD         DD
1541           18.01              1.0      0          0
812            23.09              1.0      0          0
3799           11.65              3.0     DI          0

                             ... Flujos máximos (kg/min)              \
     Pezones no encontrados  ...                      TI    TD Total
272                       0  ...                    1.44  1.50  6.18
5423                     DD  ...                    1.86  1.62  5.10
1541                      0  ...                    1.26  1.26  5.10
812                       0  ...                    1.50  3.12  9.30
3799                      0  ...                    1.08  1.02  4.92

     Producciones (kg)                            Misc
                    DI    DD    TI    TD  Total  EO/PO Destino Leche
272               3.92  3.76  4.06  4.44  16.18  VMS 3        Tanque
5423              3.01  0.00  3.63  1.92   8.56  VMS 1        Tanque
1541              3.74  3.64  5.49  5.14  18.01  VMS 3        Tanque
812               6.26  5.25  4.06  7.52  23.09  VMS 2        Tanque
3799              1.87  2.43  3.96  3.39  11.65  VMS 2        Tanque

[5 rows x 38 columns]

In [5]:
val.head()

          ID Fecha y hora de inicio                          Main  \
     ID Vaca                  fecha      hora              Acción
7208    8794             2025-06-30  13:20:00              Ordeño
6602    8758             2025-05-19  15:37:00  Echada sin ordeñar
3768    6036             2025-05-17  12:18:00              Ordeño
2879    2078             2025-06-27  13:03:00  Echada sin ordeñar
816     1554             2025-04-09  13:55:00           Rechazada

                                                Estado                    \
     Duración (mm:ss) Producción (kg) Número de ordeño Patada Incompleto
7208            05:25            7.74              2.0      0          0
6602            04:46            0.00              0.0      0          0
3768            09:26           15.43              2.0     DI          0
2879            08:43            0.00              0.0      0          0
816             00:00            0.00              0.0      0          0

                             ... Flujos máximos (kg/min)              \
     Pezones no encontrados  ...                      TI    TD Total
7208                      0  ...                    1.26  1.20  5.64
6602                      0  ...                    0.00  0.00  0.00
3768                      0  ...                    1.20  1.38  5.46
2879                      0  ...                    0.00  0.00  0.00
816                       0  ...                    0.00  0.00  0.00

     Producciones (kg)                            Misc
                    DI    DD    TI    TD  Total  EO/PO Destino Leche
7208              1.99  1.65  1.81  2.29   7.74  VMS 3        Tanque
6602              0.00  0.00  0.00  0.00   0.00  VMS 3             0
3768              2.62  3.19  5.34  4.28  15.43  VMS 2        Tanque
2879              0.00  0.00  0.00  0.00   0.00  VMS 3             0
816               0.00  0.00  0.00  0.00   0.00  VMS 2             0

[5 rows x 38 columns]

In [6]:
df.describe()

                ID         Fecha y hora de inicio            Main  \
           ID Vaca                          fecha Producción (kg)
count  7237.000000                           7237     7237.000000
mean   4923.818157  2025-05-15 07:53:10.106397696       13.283452
min    1204.000000            2025-03-01 00:00:00        0.000000
25%    1624.000000            2025-04-08 00:00:00        9.530000
50%    6036.000000            2025-05-19 00:00:00       13.040000
75%    8712.000000            2025-06-23 00:00:00       16.900000
max    8794.000000            2025-07-18 00:00:00       39.470000
std    3073.598457                            NaN        5.778454

                Estado              Media de los flujos (kg/min)               \
      Número de ordeño         Ubre                           DI           DD
count      7237.000000  7237.000000                  7237.000000  7237.000000
mean          1.717839     0.144811                     1.000044     1.069305
min           0.000000     0.000000                     0.000000     0.000000
25%           1.000000     0.000000                     0.720000     0.780000
50%           2.000000     0.000000                     1.020000     1.080000
75%           2.000000     0.000000                     1.320000     1.320000
max           5.000000     1.000000                     4.980000     2.640000
std           0.858881     0.351935                     0.463301     0.443950

                                              ... Flujos máximos (kg/min)  \
                TI           TD        Total  ...                      DI
count  7237.000000  7237.000000  7237.000000  ...             7237.000000
mean      0.975645     1.024925     4.069918  ...                1.455733
min       0.000000     0.000000     0.000000  ...                0.000000
25%       0.720000     0.780000     3.060000  ...                1.200000
50%       1.020000     1.080000     4.080000  ...                1.440000
75%       1.320000     1.320000     5.160000  ...                1.800000
max       4.080000     2.820000     9.960000  ...                4.620000
std       0.549328     0.493623     1.627252  ...                0.602697

                                                          Producciones (kg)  \
                DD           TI           TD        Total                DI
count  7237.000000  7237.000000  7237.000000  7237.000000       7237.000000
mean      1.530576     1.376885     1.480298     5.843493          3.081302
min       0.000000     0.000000     0.000000     0.000000          0.000000
25%       1.260000     1.140000     1.200000     4.800000          2.110000
50%       1.500000     1.440000     1.500000     5.820000          3.010000
75%       1.860000     1.740000     1.860000     7.200000          4.060000
max       3.420000     4.980000     4.800000    13.080000         10.420000
std       0.560020     0.737821     0.657601     2.066690          1.648646


                DD           TI           TD        Total
count  7237.000000  7237.000000  7237.000000  7237.000000
mean      3.155243     3.327445     3.719939    13.283928
min       0.000000     0.000000     0.000000     0.000000
25%       2.270000     1.930000     2.450000     9.540000
50%       3.060000     3.460000     3.710000    13.040000
75%       4.020000     4.780000     4.950000    16.900000
max       9.980000    14.310000    13.330000    39.470000
std       1.460909     2.103554     2.122039     5.778240

[8 rows x 29 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7237 entries, 582 to 179
Data columns (total 38 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   (ID, ID Vaca)                          7237 non-null   int64
 1   (Fecha y hora de inicio, fecha)        7237 non-null   datetime64[ns]
 2   (Fecha y hora de inicio, hora)         7237 non-null   object
 3   (Main, Acción)                         7237 non-null   object
 4   (Main, Duración (mm:ss))               7237 non-null   object
 5   (Main, Producción (kg))                7237 non-null   float64
 6   (Estado, Número de ordeño)             7237 non-null   float64
 7   (Estado, Patada)                       7237 non-null   object
 8   (Estado, Incompleto)                   7237 non-null   object
 9   (Estado, Pezones no encontrados)       7237 non-null   object
 10  (Estado, Ubre)                         7237 non-null   float64
 11  (Estado, Pezón)                        7237 non-null   object
 12  (Media de los flujos (kg/min), DI)     7237 non-null   float64
 13  (Media de los flujos (kg/min), DD)     7237 non-null   float64
 14  (Media de los flujos (kg/min), TI)     7237 non-null   float64
 15  (Media de los flujos (kg/min), TD)     7237 non-null   float64
 16  (Media de los flujos (kg/min), Total)  7237 non-null   float64
 17  (Sangre (ppm), DI)                     7237 non-null   float64
 18  (Sangre (ppm), DD)                     7237 non-null   float64
 19  (Sangre (ppm), TI)                     7237 non-null   float64
 20  (Sangre (ppm), TD)                     7237 non-null   float64
 21  (Conductividad (mS / cm), DI)          7237 non-null   float64
 22  (Conductividad (mS / cm), DD)          7237 non-null   float64
 23  (Conductividad (mS / cm), TI)          7237 non-null   float64
 24  (Conductividad (mS / cm), TD)          7237 non-null   float64
 25  (Conductividad (mS / cm), Total)       7237 non-null   float64
 26  (Flujos máximos (kg/min), DI)          7237 non-null   float64
 27  (Flujos máximos (kg/min), DD)          7237 non-null   float64
 28  (Flujos máximos (kg/min), TI)          7237 non-null   float64
 29  (Flujos máximos (kg/min), TD)          7237 non-null   float64
 30  (Flujos máximos (kg/min), Total)       7237 non-null   float64
 31  (Producciones (kg), DI)                7237 non-null   float64
 32  (Producciones (kg), DD)                7237 non-null   float64
 33  (Producciones (kg), TI)                7237 non-null   float64
 34  (Producciones (kg), TD)                7237 non-null   float64
 35  (Producciones (kg), Total)             7237 non-null   float64
 36  (Misc, EO/PO)                          7237 non-null   object
 37  (Misc, Destino Leche)                  7237 non-null   object
dtypes: datetime64[ns](1), float64(27), int64(1), object(9)
memory usage: 2.2+ MB

In [8]:
columnasNumericas = df.select_dtypes(include=['float64', 'int64']).columns

promediosPorVaca = df.groupby(('ID', 'ID Vaca'))[columnasNumericas].mean()

promediosPorVaca

                   ID            Main           Estado            \
              ID Vaca Producción (kg) Número de ordeño      Ubre
(ID, ID Vaca)
1204           1204.0       14.152335         1.443580  0.214008
1221           1221.0       14.217778         1.858025  0.024691
1233           1233.0        9.786182         1.537162  0.097973
1497           1497.0        2.600000         0.500000  0.000000
1554           1554.0       18.642554         1.758993  0.201439
1572           1572.0       14.629839         1.543011  0.032258
1613           1613.0       14.890618         2.052257  0.000000
1624           1624.0       16.645670         1.777778  0.056980
1634           1634.0       13.346894         1.727273  0.075758
2072           2072.0       13.905347         1.548611  0.034722
2076           2076.0       13.045660         1.747801  0.023460
2078           2078.0       10.587500         1.774194  0.341398
2082           2082.0       15.264394         1.449827  0.138408
6003           6003.0       14.583367         2.183333  0.156667
6036           6036.0       13.564659         1.902439  0.002439
6178           6178.0       16.504217         1.437751  0.650602
6191           6191.0       17.768854         2.102767  0.513834
6194           6194.0       13.553400         1.726667  0.213333
6211           6211.0       10.933829         1.575949  0.015823
6232           6232.0       11.553333         1.536232  0.028986
6238           6238.0       16.514571         1.600000  0.295238
8709           8709.0       18.474677         1.951613  0.008065
8712           8712.0       10.544371         1.774286  0.011429
8729           8729.0       12.358571         1.542125  0.146520
8732           8732.0        8.931173         1.744868  0.076246
8755           8755.0        9.065033         1.682119  0.377483
8758           8758.0       13.085840         1.504000  0.056000
8771           8771.0       10.186250         1.125000  0.750000
8777           8777.0        9.219333         1.413333  0.080000
8779           8779.0       12.652816         1.528736  0.097701
8782           8782.0        7.376503         1.453988  0.269939
8792           8792.0        7.716739         1.260870  0.108696
8794           8794.0       11.308980         1.326531  0.142857

              Media de los flujos (kg/min)                                \
                                        DI        DD        TI        TD
(ID, ID Vaca)
1204                              1.307626  1.608794  1.475720  1.624436
1221                              1.301852  0.843704  1.100000  1.118519
1233                              1.204865  1.096824  0.590270  1.293041
1497                              0.390000  0.300000  0.330000  0.300000
1554                              1.671799  1.444748  1.430072  1.558705
1572                              1.369677  1.175806  1.056774  1.257419
1613                              0.693777  0.779287  0.779715  0.867363
1624                              1.049402  1.095556  1.228205  1.169231
1634                              0.918636  1.235000  0.774091  0.804545
2072                              0.843333  1.512083  1.125000  1.147083
2076                              1.134018  1.199472  1.523402  1.486276
2078                              0.662742  0.653065  0.874355  0.922419
2082                              1.008997  1.082491  1.109689  1.029550
6003                              1.798800  1.820600  1.221400  1.606600
6036                              0.783512  0.886976  0.770049  0.639220
6178                              1.288434  1.615181  1.166506  1.033494
6191                              0.667115  0.722372  0.821028  1.071700
6194                              1.201600  0.990800  1.056800  1.076800
6211                              0.728734  0.748101  0.000000  0.892595
6232                              1.064348  0.649565  1.529565  0.000000
6238                              1.594286  1.527429  1.862857  1.541143
8709                              0.911855  1.005968  0.848468  0.802258
8712                              1.212343  1.335429  1.317257  1.166057
8729                              0.796484  1.137363  0.896264  0.857363
8732                              0.404516  0.649619  0.859003  0.610205
8755                              0.488742  0.770662  0.399735  0.288874
8758                              1.629120  1.336800  1.397280  1.443360
8771                              1.102500  0.877500  1.207500  1.050000
8777                              0.797600  0.796000  0.662400  0.561600
8779                              1.035862  1.123448  1.012759  1.086552
8782                              0.387239  0.471534  0.374724  0.332393
8792                              1.295217  1.270435  1.207826  0.860870
8794                              1.121633  1.089796  0.983265  0.929388

                        Sangre (ppm)  ... Flujos máximos (kg/min)            \
                  Total           DI  ...                      DI        DD
(ID, ID Vaca)                         ...
1204           6.016576     4.754864  ...                1.850428  2.154163
1221           4.364074   107.012346  ...                1.867037  1.493704
1233           4.185000     0.000000  ...                1.678581  1.512162
1497           1.320000  3998.500000  ...                0.570000  0.660000
1554           6.105324     2.769784  ...                2.178129  1.889353
1572           4.859677    85.715054  ...                1.844839  1.617419
1613           3.120143     0.000000  ...                1.122470  1.246603
1624           4.542393     1.085470  ...                1.497607  1.598974
1634           3.732273    16.136364  ...                1.383182  1.671818
2072           4.627500    93.944444  ...                1.333750  2.026250
2076           5.343167     0.926686  ...                1.579355  1.691261
2078           3.112581     7.405914  ...                1.049839  1.035645
2082           4.230727     0.000000  ...                1.462630  1.583875
6003           6.447400     0.000000  ...                2.595800  2.475400
6036           3.079756     0.000000  ...                1.266878  1.304780
6178           5.103614     3.088353  ...                1.828916  2.240241
6191           3.282213     0.000000  ...                1.087826  1.143320
6194           4.326000     0.000000  ...                1.638000  1.434000
6211           2.369430     1.158228  ...                1.181962  1.166962
6232           3.243478   127.449275  ...                1.511304  1.014783
6238           6.525714   162.419048  ...                2.170286  2.055429
8709           3.568548    18.346774  ...                1.378548  1.477500
8712           5.031086     0.000000  ...                1.622229  1.785429
8729           3.687473     2.622711  ...                1.171868  1.528352
8732           2.523343     0.000000  ...                0.647273  1.017713
8755           1.948013     0.000000  ...                0.842384  1.203576
8758           5.806560    22.504000  ...                2.159520  1.773120
8771           4.237500  4295.625000  ...                1.522500  1.297500
8777           2.817600   144.426667  ...                1.224800  1.156800
8779           4.258621    22.442529  ...                1.451379  1.535172
8782           1.565890    39.447853  ...                0.699387  0.823436
8792           4.634348    68.913043  ...                1.806522  1.741304
8794           4.124082   129.959184  ...                1.578367  1.515918

                                            Producciones (kg)            \
                     TI        TD     Total                DI        DD
(ID, ID Vaca)
1204           1.950350  2.091595  8.046537          3.855603  3.401984
1221           1.511358  1.561852  6.433951          3.339321  3.240494
1233           0.875878  1.761486  5.828108          3.136959  2.653682
1497           0.540000  0.450000  2.220000          0.680000  0.440000
1554           1.882662  2.256043  8.206187          5.215072  4.010576
1572           1.497419  1.698387  6.658065          3.123871  3.134140
1613           1.271544  1.292637  4.933254          2.987601  2.930546
1624           1.624900  1.699145  6.420627          4.106097  3.025100
1634           1.129545  1.200000  5.384545          3.773106  3.918182
2072           1.597083  1.596250  6.553333          3.402778  3.067569
2076           2.045396  2.067097  7.383109          2.752199  3.221730
2078           1.238495  1.386613  4.710591          2.026694  2.642527
2082           1.484567  1.526990  6.058062          4.058201  1.624567
6003           1.645400  2.233600  8.950200          3.683833  4.269733
6036           1.174244  1.084098  4.830000          2.315000  2.751171
6178           1.610120  1.530843  7.210120          3.675181  4.873253
6191           1.222925  1.509249  4.963320          3.497945  3.935889
6194           1.542000  1.490800  6.104800          3.599733  2.393267
6211           0.000000  1.338418  3.687342          3.265443  2.696519
6232           1.989565  0.000000  4.515652          3.426957  2.617681
6238           2.543429  2.080000  8.849143          3.365143  2.719905
8709           1.315161  1.264597  5.435806          5.113145  4.490806
8712           1.741829  1.588286  6.737771          2.478514  2.724114
8729           1.309451  1.245934  5.255604          1.554982  3.735568
8732           1.227390  0.977947  3.870323          1.186422  2.506276
8755           0.695563  0.547550  3.289073          2.122550  4.086159
8758           1.851840  1.884320  7.668800          3.516400  3.358640
8771           1.635000  1.485000  5.940000          2.440000  2.710000
8777           1.104000  0.902400  4.388000          2.093200  2.193733
8779           1.432414  1.535862  5.954828          2.887241  2.752414
8782           0.708221  0.638650  2.869693          1.765460  2.260736
8792           1.766087  1.373478  6.687391          2.119348  2.188913
8794           1.388571  1.335918  5.818776          2.634694  2.451633


                     TI        TD      Total
(ID, ID Vaca)
1204           2.002529  4.892218  14.152335
1221           3.847963  3.790000  14.217778
1233           0.767399  3.228142   9.786182
1497           0.735000  0.745000   2.600000
1554           3.556223  5.860683  18.642554
1572           4.287473  4.084355  14.629839
1613           4.659881  4.312589  14.890618
1624           5.150427  4.364046  16.645670
1634           2.527273  3.128333  13.346894
2072           3.389653  4.045347  13.905347
2076           3.281144  3.790587  13.045660
2078           2.900753  3.017527  10.587500
2082           4.923979  4.657647  15.264394
6003           2.732667  3.897133  14.583367
6036           4.569293  3.929195  13.564659
6178           4.363012  3.592771  16.504217
6191           3.874387  6.460632  17.768854
6194           3.855000  3.705400  13.553400
6211           0.000000  4.971867  10.933829
6232           5.508696  0.000000  11.553333
6238           4.985714  5.443810  16.514571
8709           4.504637  4.366089  18.474677
8712           2.763000  2.578743  10.544371
8729           3.677143  3.390879  12.358571
8732           3.274956  1.973636   8.941290
8755           1.712252  1.144073   9.065033
8758           3.179040  3.031760  13.085840
8771           2.963750  2.072500  10.186250
8777           2.631333  2.301067   9.219333
8779           3.359943  3.653218  12.652816
8782           1.995767  1.354540   7.376503
8792           1.856304  1.552174   7.716739
8794           2.822857  3.399796  11.308980

[33 rows x 28 columns]

In [9]:
print(df.columns.names)
print(df.columns.levels)

[None, None]
[['Conductividad (mS / cm)', 'Estado', 'Flujos máximos (kg/min)', 'ID', 'Main', 'Media de los flujos (kg/min)', 'Misc', 'Producciones (kg)', 'Sangre (ppm)', 'Fecha y hora de inicio'], ['Acción', 'DD', 'DI', 'Destino Leche', 'Duración (mm:ss)', 'EO/PO', 'Hora de inicio', 'ID Vaca', 'Incompleto', 'Número de ordeño', 'Patada', 'Pezones no encontrados', 'Pezón', 'Producción (kg)', 'Razón de la desviación', 'TD', 'TI', 'Ubre', 'fecha', 'hora', 'Total']]

In [10]:
flujosColumns = df.xs('Media de los flujos (kg/min)', axis=1, level=0)

flujosColumns

        DI    DD    TI    TD  Total
582   1.20  0.96  0.84  1.38   4.38
4067  1.38  1.80  1.44  1.44   6.06
4421  0.60  0.72  1.56  1.14   4.02
193   1.38  1.80  0.00  1.74   4.92
2888  0.90  0.60  1.20  0.96   3.66
...    ...   ...   ...   ...    ...
5162  0.84  1.02  0.84  0.78   3.48
2153  0.78  1.56  1.02  1.20   4.56
3577  1.02  0.90  0.66  0.66   3.24
1436  0.78  0.84  0.78  0.90   3.30
179   1.38  1.50  1.38  1.44   5.70

[7237 rows x 5 columns]

In [11]:
df.groupby(('ID', 'ID Vaca')).count()[('Main', 'Acción')]

(ID, ID Vaca)
1204    257
1221    162
1233    296
1497      2
1554    278
1572    186
1613    421
1624    351
1634    132
2072    144
2076    341
2078    372
2082    289
6003    300
6036    410
6178    249
6191    253
6194    150
6211    316
6232     69
6238    105
8709    248
8712    350
8729    273
8732    341
8755    302
8758    125
8771      8
8777     75
8779    174
8782    163
8792     46
8794     49
Name: (Main, Acción), dtype: int64

In [ ]:
# Obtener fecha min y max por vaca
fechas_por_vaca = (
    df.groupby(['ID', 'ID Vaca'])[('Fecha y hora de inicio', 'fecha')]
      .agg(['min', 'max'])
      .reset_index()
)

# Para renombrar las columnas para mejor claridad
fechas_por_vaca.columns = ['Primera_fecha', 'Ultima_fecha']

# Para ver también la cantidad de días entre la primera y última fecha
fechas_por_vaca['Dias_totales'] = (fechas_por_vaca['Ultima_fecha'] - fechas_por_vaca['Primera_fecha']).dt.days

print(fechas_por_vaca)

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.