In [3]:
from util.load_dataframe import load_dataframe

load_dataframe('datos/registros_sesiones_merged.csv')

          ID                    Main                                           \
     ID Vaca          Hora de inicio  Acción Duración (mm:ss) Producción (kg)
0       1204  02/03/2025 02:24 a. m.  Ordeño            07:23           11.13
1       1204  02/03/2025 07:51 p. m.  Ordeño            08:29           20.64
2       1204  03/03/2025 06:00 a. m.  Ordeño            05:05            9.59
3       1204  04/03/2025 12:16 a. m.  Ordeño            09:07           22.58
4       1204  04/03/2025 06:27 p. m.  Ordeño            12:09           22.71
...      ...                     ...     ...              ...             ...
7232    8794  15/07/2025 07:22 p. m.  Ordeño            07:14           10.17
7233    8794  16/07/2025 02:31 p. m.  Ordeño            06:57           15.63
7234    8794  17/07/2025 02:30 a. m.  Ordeño            05:44           11.23
7235    8794  17/07/2025 02:18 p. m.  Ordeño            05:32           11.65
7236    8794  18/07/2025 04:01 a. m.  Ordeño            06:17           13.48

               Estado                                                ...  \
     Número de ordeño Patada Incompleto Pezones no encontrados Ubre  ...
0                 1.0    NaN        NaN                    NaN  1.0  ...
1                 2.0    NaN        NaN                    NaN  1.0  ...
2                 1.0    NaN        NaN                    NaN  1.0  ...
3                 1.0    NaN        NaN                    NaN  1.0  ...
4                 2.0    NaN        NaN                    NaN  1.0  ...
...               ...    ...        ...                    ...  ...  ...
7232              2.0    NaN        NaN                    NaN  0.0  ...
7233              1.0    NaN        NaN                    NaN  0.0  ...
7234              1.0    NaN        NaN                    NaN  0.0  ...
7235              2.0    NaN        NaN                    NaN  0.0  ...
7236              1.0    NaN        NaN                    NaN  0.0  ...

              Misc Flujos máximos (kg/min)                    \
     Destino Leche                      DI    DD    TI    TD
0           Tanque                    1.68  1.98  2.34  1.92
1           Tanque                    2.10  2.22  2.52  2.40
2           Tanque                    1.80  2.10  2.28  1.98
3           Tanque                    1.98  2.40  2.28  1.98
4           Tanque                    1.80  2.34  2.34  2.28
...            ...                     ...   ...   ...   ...
7232        Tanque                    1.50  1.62  1.56  1.44
7233        Tanque                    1.74  1.56  1.44  1.32
7234        Tanque                    1.50  1.44  1.32  1.32
7235        Tanque                    1.56  1.44  1.38  1.38
7236        Tanque                    1.62  1.44  1.62  1.32

     Producciones (kg)                                     Misc
                    DI    DD    TI    TD Razón de la desviación
0                 4.40  2.43  1.15  3.15                    NaN
1                 5.72  4.88  3.10  6.94                    NaN
2                 2.69  2.41  1.44  3.05                    NaN
3                 6.05  5.05  3.58  7.90                    NaN
4                 6.26  5.31  3.47  7.67                    NaN
...                ...   ...   ...   ...                    ...
7232              2.27  2.31  2.49  3.10                    NaN
7233              3.53  3.49  3.81  4.80                    NaN
7234              2.47  2.48  2.91  3.37                    NaN
7235              2.66  2.59  2.93  3.47                    NaN
7236              3.05  2.91  3.53  3.99                    NaN

[7237 rows x 34 columns]