In [1]:
from util.load_dataframes import load_dataframe_vacas, load_dataframe_patadas, load_dataframe_inventario, load_dataframe_reporte


df = load_dataframe_vacas('datos/registros_sesiones_merged.csv')
df = df.sample(frac=1)
df.head()

          ID    Main                                            Estado         \
     ID Vaca  Acción Duración (mm:ss) Producción (kg) Número de ordeño Patada
6556    8755  Ordeño            13:39            9.59              1.0     DI
6715    8758  Ordeño            04:53           10.56              2.0      0
2499    2076  Ordeño            10:33           13.85              1.0      0
7055    8782  Ordeño            10:37            2.24              1.0     TD
1097    1572  Ordeño            06:54           14.37              1.0      0

                                                   ...  \
     Incompleto Pezones no encontrados Ubre Pezón  ...
6556          0                     TI  0.0     0  ...
6715          0                      0  0.0     0  ...
2499          0                      0  0.0     0  ...
7055   DD,TI,TD                  DD,TI  0.0     0  ...
1097          0                      0  0.0     0  ...

     Flujos máximos (kg/min)                   Producciones (kg)              \
                          DI    DD    TI    TD                DI    DD    TI
6556                    1.38  1.38  0.00  0.72              1.45  4.71  0.00
6715                    1.92  1.86  1.92  1.86              2.78  2.71  2.45
2499                    1.98  1.80  2.16  2.28              3.43  3.18  3.37
7055                    0.78  0.00  0.00  1.08              1.90  0.00  0.00
1097                    1.80  1.68  1.50  1.80              2.95  2.92  4.35

           Fecha y hora de inicio
        TD                  fecha      hora
6556  3.43             2025-07-01  06:31:00
6715  2.62             2025-07-15  16:53:00
2499  3.87             2025-06-20  10:00:00
7055  0.34             2025-06-01  07:11:00
1097  4.15             2025-04-22  00:06:00

[5 rows x 34 columns]

In [2]:
from util.split_dataframes import split_dataframe

train, test, val = split_dataframe(df, 70, 15, 15)

In [3]:
train.head()

          ID    Main                                            Estado         \
     ID Vaca  Acción Duración (mm:ss) Producción (kg) Número de ordeño Patada
6556    8755  Ordeño            13:39            9.59              1.0     DI
6715    8758  Ordeño            04:53           10.56              2.0      0
2499    2076  Ordeño            10:33           13.85              1.0      0
7055    8782  Ordeño            10:37            2.24              1.0     TD
1097    1572  Ordeño            06:54           14.37              1.0      0

                                                   ...  \
     Incompleto Pezones no encontrados Ubre Pezón  ...
6556          0                     TI  0.0     0  ...
6715          0                      0  0.0     0  ...
2499          0                      0  0.0     0  ...
7055   DD,TI,TD                  DD,TI  0.0     0  ...
1097          0                      0  0.0     0  ...

     Flujos máximos (kg/min)                   Producciones (kg)              \
                          DI    DD    TI    TD                DI    DD    TI
6556                    1.38  1.38  0.00  0.72              1.45  4.71  0.00
6715                    1.92  1.86  1.92  1.86              2.78  2.71  2.45
2499                    1.98  1.80  2.16  2.28              3.43  3.18  3.37
7055                    0.78  0.00  0.00  1.08              1.90  0.00  0.00
1097                    1.80  1.68  1.50  1.80              2.95  2.92  4.35

           Fecha y hora de inicio
        TD                  fecha      hora
6556  3.43             2025-07-01  06:31:00
6715  2.62             2025-07-15  16:53:00
2499  3.87             2025-06-20  10:00:00
7055  0.34             2025-06-01  07:11:00
1097  4.15             2025-04-22  00:06:00

[5 rows x 34 columns]

In [4]:
test.head()

          ID    Main                                            Estado         \
     ID Vaca  Acción Duración (mm:ss) Producción (kg) Número de ordeño Patada
2220    2072  Ordeño            08:20           16.53              1.0      0
3525    6003  Ordeño            05:47           11.66              4.0      0
905     1554  Ordeño            08:25           23.92              2.0      0
2169    2072  Ordeño            06:30           13.01              1.0      0
1256    1613  Ordeño            10:52           19.26              1.0     TD

                                                   ...  \
     Incompleto Pezones no encontrados Ubre Pezón  ...
2220          0                      0  0.0     0  ...
3525          0                      0  1.0     0  ...
905           0                      0  0.0     0  ...
2169          0                      0  0.0     0  ...
1256          0                      0  0.0     0  ...

     Flujos máximos (kg/min)                   Producciones (kg)              \
                          DI    DD    TI    TD                DI    DD    TI
2220                    1.44  2.52  1.68  1.68              4.42  3.74  3.94
3525                    2.22  3.24  2.82  2.40              2.30  3.79  2.46
905                     2.04  1.80  1.98  2.94              6.57  4.62  4.73
2169                    1.20  2.10  1.44  1.50              2.77  2.95  3.10
1256                    1.20  1.32  1.32  1.26              3.86  3.75  5.96

           Fecha y hora de inicio
        TD                  fecha      hora
2220  4.43             2025-07-15  11:35:00
3525  3.11             2025-07-16  22:25:00
905   8.00             2025-05-21  21:45:00
2169  4.19             2025-04-12  10:41:00
1256  5.69             2025-03-24  08:04:00

[5 rows x 34 columns]

In [5]:
val.head()

          ID    Main                                            Estado         \
     ID Vaca  Acción Duración (mm:ss) Producción (kg) Número de ordeño Patada
5708    8729  Ordeño            08:07           16.07              2.0      0
7129    8782  Ordeño            12:35           13.23              1.0      0
2395    2076  Ordeño            08:56           23.51              1.0     DI
4082    6178  Ordeño            08:28           19.05              2.0      0
3203    2082  Ordeño            06:38           11.06              1.0      0

                                                   ...  \
     Incompleto Pezones no encontrados Ubre Pezón  ...
5708          0                      0  0.0     0  ...
7129          0                      0  0.0    TI  ...
2395          0                      0  0.0     0  ...
4082          0                      0  1.0     0  ...
3203          0                      0  0.0     0  ...

     Flujos máximos (kg/min)                   Producciones (kg)              \
                          DI    DD    TI    TD                DI    DD    TI
5708                    1.02  1.44  1.14  1.20              2.07  4.91  4.35
7129                    1.08  0.96  3.24  0.84              2.77  3.31  4.71
2395                    1.98  1.86  2.52  2.52              5.20  5.41  6.35
4082                    2.04  2.28  1.80  1.74              3.44  6.02  4.80
3203                    1.08  1.74  1.56  1.38              3.02  0.94  3.78

           Fecha y hora de inicio
        TD                  fecha      hora
5708  4.74             2025-03-17  21:39:00
7129  2.44             2025-07-11  02:50:00
2395  6.55             2025-05-10  00:11:00
4082  4.79             2025-05-18  18:11:00
3203  3.32             2025-07-04  11:21:00

[5 rows x 34 columns]